miniImageNet:
  # Parameter
  feature_dim : 640
  
  # Network
  inner_update_step : 3 # number of synthetic gradient steps

  # Optimizer
  meta_lr : 1.0e-3 # lr is fixed
  inner_lr: 1.0e-3 # lr is fixed
  weightDecay: 0.0005 
  momentum: 0.9 

  # Training details
  coefficient_synthetic_grad_loss : 0 # grad loss coeff

   # name (Just for matching directory name)
  encoder_type : "ResNet_28_10"
  beta_kl : 0
